
package poo.javacomp.ventanas;

import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.util.Date;
import poo.javacomp.logica.Cliente;
import poo.javacomp.logica.ClienteParticular;
import poo.javacomp.logica.ClienteEmpresa;
import poo.javacomp.logica.RecursosApp;
import java.util.ArrayList;
import java.util.ListIterator;
import javax.swing.JOptionPane;

public class ConsultaClientes extends javax.swing.JFrame {
    private ArrayList<Cliente> clienteAux;      //Referencia al ArrayList de clientes de la clase RecursosApp
    private ListIterator<Cliente> iterador;     //Iterador para recorrer el ArrayList
    private Cliente objCliente;                 //Referencia a un objeto del tipo cliente del ArrayList
    private VentanaAdmin ventanaAdmin;
    
    /** Creates new form ConsultaClientes
     @param ventana
     */
    public ConsultaClientes(VentanaAdmin ventana) {
        initComponents();
        ventanaAdmin = ventana;
        ventanaAdmin.setVisible(false);
        panelUsuarios.desactivaTodo();
        jTextFieldTipo.setEditable(false);
        consultarTodo();
        this.setVisible(true);
    }

    /** Consulta los clientes del ArrayList ordenados para su presentación */
    private void consultarTodo() {
        try {
            clienteAux = RecursosApp.getClientes();
            iterador = clienteAux.listIterator();
            if (clienteAux.size() < 1) {
                JOptionPane.showMessageDialog(this, "No hay clientes", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                jButtonSiguiente.setEnabled(false);
                jButtonAnterior.setEnabled(false);
                return;
            } else {
                jButtonSiguiente.setEnabled(true);
                jButtonAnterior.setEnabled(true);
            }
            if (iterador.hasNext()) {
                objCliente = iterador.next();
            }
            if (objCliente != null) {
                presenta(objCliente);
            } else {
                JOptionPane.showMessageDialog(this, "No hay clientes", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + e.toString());
        }
    }//fin consultarTodo

    /** Presenta los datos de un cliente en el panel de datos */
    private void presenta(Cliente cliente) {
        String tipo = cliente.getClass().getSimpleName();
        panelUsuarios.setJTextFieldNombre(cliente.getNombre());
        panelUsuarios.setJTextFieldCorreo(cliente.getCorreo());
        panelUsuarios.setJTextFieldClave(cliente.getClave());
        
        panelUsuarios.setJTextFieldCalle(cliente.getDireccion().getCalle());
        String numero = Integer.toString(cliente.getDireccion().getNumero());
        panelUsuarios.setJFormattedTextFieldDireccionNumero(numero);
        String codigoPostal = Integer.toString(cliente.getDireccion().getCodigoPostal());
        panelUsuarios.setJFormattedTextFieldCodigoPostal(codigoPostal);
        panelUsuarios.setJTextFieldCiudad(cliente.getDireccion().getCiudad());
        
        panelUsuarios.setJTextFieldTarjetaNombre(cliente.getTarjetaCredito().getNombreTitular());
        String tarjetaNumero = Long.toString(cliente.getTarjetaCredito().getNumero());
        panelUsuarios.setJFormattedTextFieldTarjetaNumero(tarjetaNumero);
        SimpleDateFormat formatoCorto = new SimpleDateFormat("MM/yy");
        Date f = cliente.getTarjetaCredito().getFechaCaducidad();
        String fecha = formatoCorto.format(f);
        panelUsuarios.setJFormattedTextFieldTarjetaFecha(fecha + "");
        
        String telefono = Long.toString(cliente.getTelefono());
        panelUsuarios.setJFormattedTextFieldTelefono(telefono + "");
        
        if (tipo.equals("ClienteParticular")) {
            ClienteParticular particular = (ClienteParticular) cliente;
            jTextFieldTipo.setText("Particular");
            panelUsuarios.setJLabelDniCif("DNI:");
            panelUsuarios.setJTextFieldDniCif(particular.getDni());
        } else {
            ClienteEmpresa empresa = (ClienteEmpresa) cliente;
            jTextFieldTipo.setText("Empresa");
            panelUsuarios.setJLabelDniCif("CIF:");
            panelUsuarios.setJTextFieldDniCif(empresa.getCif());
            panelUsuarios.setJTextFieldWeb(empresa.getWeb());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAnterior = new javax.swing.JButton();
        panelUsuarios = new poo.javacomp.ventanas.PanelUsuarios();
        jButtonSiguiente = new javax.swing.JButton();
        jTextFieldTipo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-50.png"))); // NOI18N
        jLabel1.setText("Consulta Clientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButtonAnterior.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAnterior.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jButtonAnterior.setText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonSiguiente.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSiguiente.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        jLabel2.setText("Tipo de Cliente:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGORedimensionado.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(74, 74, 74)
                .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButtonAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSiguiente)
                .addGap(78, 78, 78)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(panelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSiguiente)
                            .addComponent(jButtonAnterior))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //ANTERIOR
    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        if (iterador.hasPrevious()) {
        objCliente = iterador.previous();
        if (objCliente != null) {
            presenta(objCliente);
        } else {
            JOptionPane.showMessageDialog(this, "No hay clientes.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    //SIGUIENTE
    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        if (iterador.hasNext()) {
        objCliente = iterador.next();
        if (objCliente != null) {
            presenta(objCliente);
        } else {
            JOptionPane.showMessageDialog(this, "No hay clientes.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ventanaAdmin.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldTipo;
    private poo.javacomp.ventanas.PanelUsuarios panelUsuarios;
    // End of variables declaration//GEN-END:variables
}
