
package poo.javacomp.ventanas;

import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.ListIterator;
import javax.swing.JOptionPane;
import poo.javacomp.logica.RecursosApp;
import poo.javacomp.logica.Producto;
import java.time.LocalDate;
import javax.swing.ImageIcon;

public class ConsultaProductos extends javax.swing.JFrame {
    private ArrayList<Producto> productosAux;       //Referencia al ArrayList de productos de la clase RecursosApp
    private ListIterator<Producto> iterador;        //Iterador para recorrer el ArrayList
    private Producto objProducto;                   //Referencia a un objeto del tipo producto del ArrayList
    private VentanaAdmin ventanaAdmin;
    /**
     * Creates new form ConsultaProductos
     * @param ventana
     */
    public ConsultaProductos(VentanaAdmin ventana) {
        initComponents();
        ventanaAdmin = ventana;
        ventanaAdmin.setVisible(false);
        panelProductos.desactivaStock();
        panelProductos.desactivaTitulo();
        consultarTodo();
        this.setVisible(true);
    }

    /** Consulta los productos del ArrayList ordenados para su presentación */
    private void consultarTodo() {
        try {
            productosAux = RecursosApp.getProductos();
            iterador = productosAux.listIterator();
            if (productosAux.size() < 1) {
                JOptionPane.showMessageDialog(this, "No hay productos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                jButtonSiguiente.setEnabled(false);
                jButtonAnterior.setEnabled(false);
                jButtonBaja.setEnabled(false);
                jButtonModificar.setEnabled(false);
                jButtonReponer.setEnabled(false);
                return;
            } else {
                jButtonSiguiente.setEnabled(true);
                jButtonAnterior.setEnabled(true);
                jButtonBaja.setEnabled(true);
                jButtonModificar.setEnabled(true);
                jButtonReponer.setEnabled(true);
            }
            //presentamos 
            if (iterador.hasNext()) {
                objProducto = iterador.next();
            }
            if (objProducto != null) {
                presenta(objProducto);
            } else {
                JOptionPane.showMessageDialog(this, "No hay productos", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
            System.out.println("Error: " + e.toString());
        }
    }//fin consultarTodo

    /** Presenta los datos de un producto en el panel de datos */
    private void presenta(Producto p) {
        panelProductos.setJTextFieldTitulo(p.getTitulo());
        panelProductos.setJTextFieldCaracteristicas(p.getCaracteristicas());
        panelProductos.setJComboBoxCategoria(p.getCategoria());
        panelProductos.setJFormattedTextFieldPrecio(p.getPrecio() + "");
        panelProductos.setJFormattedTextFieldStock(p.getStock() + "");
        panelProductos.setJFormattedTextFieldFecha(p.getFechaEntrada() + "");
        
        String imagentxt = panelProductos.getJTextFieldTitulo().replace(" ", "");
        ImageIcon imagen = new ImageIcon("./imagenes/" + imagentxt);
        ImageIcon imgRedimensionada = new ImageIcon(imagen.getImage().getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), 1));
        jLabelImagen.setIcon(imgRedimensionada);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();
        panelProductos = new poo.javacomp.ventanas.PanelProductos();
        jButtonModificar = new javax.swing.JButton();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jButtonReponer = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonBaja = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        jLabel1.setText("Consulta Productos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jButtonModificar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonModificar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonReponer.setBackground(new java.awt.Color(255, 255, 255));
        jButtonReponer.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jButtonReponer.setText("Reponer");
        jButtonReponer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReponerActionPerformed(evt);
            }
        });

        jButtonAnterior.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAnterior.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jButtonAnterior.setText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonBaja.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBaja.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jButtonBaja.setText("Baja Producto");
        jButtonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBajaActionPerformed(evt);
            }
        });

        jButtonSiguiente.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSiguiente.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGORedimensionado.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButtonModificar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jButtonAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSiguiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReponer, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBaja)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonReponer)
                            .addComponent(jSpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAnterior)
                            .addComponent(jButtonSiguiente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModificar)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonBaja)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // SIGUIENTE
    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        // TODO add your handling code here:
        try {
            if (iterador.hasNext()) {
                objProducto = iterador.next();
                if (objProducto != null) {
                    presenta(objProducto);
                } else {
                    JOptionPane.showMessageDialog(this, "No hay productos", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Excepción:  " + e.toString(), "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    // ANTERIOR
    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
        try {
            if (iterador.hasPrevious()) {
                objProducto = iterador.previous();
                if (objProducto != null) {
                    presenta(objProducto);
                } else {
                    JOptionPane.showMessageDialog(this, "No hay productos", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Excepción:  " + e.toString(), "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    // BAJA
    private void jButtonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBajaActionPerformed

        if (objProducto != null) {
            iterador.remove();
            JOptionPane.showMessageDialog(this, "Producto dado de baja." , "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Producto no encontrado.", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        if (iterador.hasNext()) {
            objProducto = iterador.next();
            if (objProducto != null) {
                presenta(objProducto);
            } else {
                JOptionPane.showMessageDialog(this, "No hay productos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        } else if (iterador.hasPrevious()) {
            objProducto = iterador.previous();
            if (objProducto != null) {
                presenta(objProducto);
            } else {
                JOptionPane.showMessageDialog(this, "No hay productos.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonBajaActionPerformed

    // REPONER
    private void jButtonReponerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReponerActionPerformed
        // TODO add your handling code here:
        try {
            int cantidad = (Integer) jSpinnerCantidad.getValue();
            int stock = objProducto.getStock();
            if (cantidad > 0){
            String tipo = objProducto.getClass().getSimpleName();
            objProducto.setStock(cantidad + stock);
            JOptionPane.showMessageDialog(this, "Ahora hay " + objProducto.getStock() + " unidades.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            presenta(objProducto);
            } else {
                JOptionPane.showMessageDialog(this, "No introduzca valores negativos", "Mensaje", JOptionPane.ERROR_MESSAGE);
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error al comprar: " + e.toString(), "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonReponerActionPerformed

    // MODIFICAR
    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        try {
            String caracteristicas = panelProductos.getJTextFieldCaracteristicas();
            String categoria = panelProductos.getJComboBoxCategoria();
            double precio = Double.parseDouble(panelProductos.getJFormattedTextFieldPrecio());
            int stock = Integer.parseInt(panelProductos.getJFormattedTextFieldStock());
            LocalDate fecha = LocalDate.parse(panelProductos.getJFormattedTextFieldFecha());
            
            if (RecursosApp.modificaProducto(objProducto, caracteristicas, categoria, precio, stock, fecha)) {
                JOptionPane.showMessageDialog(this, "Producto modificado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Producto no encontrado", "Mensaje", JOptionPane.ERROR_MESSAGE);
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error al modificar: " + e.toString(), "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        ventanaAdmin.setVisible(true);
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonBaja;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonReponer;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinnerCantidad;
    private poo.javacomp.ventanas.PanelProductos panelProductos;
    // End of variables declaration//GEN-END:variables
}
