
package poo.javacomp.ventanas;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import poo.javacomp.logica.Cliente;
import poo.javacomp.logica.ClienteEmpresa;
import poo.javacomp.logica.ClienteParticular;
import poo.javacomp.logica.Direccion;
import poo.javacomp.logica.TarjetaCredito;
import poo.javacomp.logica.RecursosApp;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class VentanaRegistro extends javax.swing.JFrame {

    private VentanaPrincipal ventanaPrincipal;
    private Cliente cliente;                        //Referencia al cliente que se da de alta
    private String tipo = "";                       //Referencia al tipo de cliente
    
    /**
     * Creates new form VentanaRegistro
     * @param ventana
     */
    public VentanaRegistro(VentanaPrincipal ventana) {
        ventanaPrincipal = ventana;
        ventanaPrincipal.setVisible(false);
        initComponents();
        this.setVisible(true);
        jComboBoxTipo.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        panelUsuarios = new poo.javacomp.ventanas.PanelUsuarios();
        jButtonRegistro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jComboBoxTipo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particular", "Empresa" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jButtonRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegistro.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jButtonRegistro.setText("REGISTRARSE");
        jButtonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        jLabel2.setText("Tipo de Cliente:");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Arial Nova", 1, 36)); // NOI18N
        jLabel1.setText("Registro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGORedimensionado.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonRegistro)
                        .addGap(135, 135, 135)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRegistro)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //REGISTRARSE
    private void jButtonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroActionPerformed
        // TODO add your handling code here:
    try { 
        Pattern pattern = Pattern
                .compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        
        String dniCif = panelUsuarios.getJTextFieldDniCif();
        String nombre = panelUsuarios.getJTextFieldNombre();
        String correo = panelUsuarios.getJTextFieldCorreo();
        Matcher matcher = pattern.matcher(correo);
        String clave = panelUsuarios.getJTextFieldClave();
        
        String calle = panelUsuarios.getJTextFieldCalle();
        int numCalle = Integer.parseInt(panelUsuarios.getJFormattedTextFieldDireccionNumero());
        int codigoPostal = Integer.parseInt(panelUsuarios.getJFormattedTextFieldCodigoPostal());
        String ciudad = panelUsuarios.getJTextFieldCiudad();
        Direccion direccion = new Direccion(calle, numCalle, codigoPostal, ciudad);
        
        String nombreTarjeta = panelUsuarios.getJTextFieldTarjetaNombre();
        SimpleDateFormat formato = new SimpleDateFormat("MM/yy");
        Date hoy = new Date();
        Date fechaTarjeta = formato.parse(panelUsuarios.getJFormattedTextFieldTarjetaFecha());
        long numTarjeta = Long.parseLong(panelUsuarios.getJFormattedTextFieldTarjetaNumero());
        TarjetaCredito tarjetaCredito = new TarjetaCredito(nombreTarjeta, numTarjeta, fechaTarjeta);
        
        long telefono = Long.parseLong(panelUsuarios.getJFormattedTextFieldTelefono());
        String web = panelUsuarios.getJTextFieldWeb();
        
        if (fechaTarjeta.after(hoy)){
            if ((panelUsuarios.getJFormattedTextFieldTarjetaNumero()).length() == 16){
                String tipo = (String) jComboBoxTipo.getSelectedItem();
                if (matcher.find()) {
                    if (tipo.equals("Particular")) {
                        cliente = new ClienteParticular(dniCif, nombre, correo, clave, direccion, tarjetaCredito, telefono);
                        if (RecursosApp.altaCliente(cliente)) {
                            JOptionPane.showMessageDialog(this, "Persona dada de alta.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(this, "Error al dar de alta.", "Mensaje", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        if (web.equals("")){
                            JOptionPane.showMessageDialog(this, "Introduzca una web correcta", "Mensaje", JOptionPane.ERROR_MESSAGE);
                        } else {
                            cliente = new ClienteEmpresa(dniCif, web, nombre, correo, clave, direccion, tarjetaCredito, telefono);
                            if (RecursosApp.altaCliente(cliente)) {
                                JOptionPane.showMessageDialog(this, "Persona dada de alta.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                            } else {
                                JOptionPane.showMessageDialog(this, "Error al dar de alta.", "Mensaje", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                    } 
                } else {
                    JOptionPane.showMessageDialog(this, "Introduzca un correo válido", "Mensaje", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Introduzca un número de tarjeta de 16 cifras", "Mensaje", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe introducir una tarjeta no caducada", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (Exception e){
        JOptionPane.showMessageDialog(this, "Excepción al dar de alta. Introduzca todos los datos correctamente.", "Mensaje", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButtonRegistroActionPerformed

    // ELEGIR TIPO DE CLIENTE
    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
        tipo = (String) jComboBoxTipo.getSelectedItem();
        if (tipo.equals("Particular")) {
            panelUsuarios.setJLabelDniCif("DNI:");
            panelUsuarios.setEditableJTextFieldWeb(false);
        } else {
            panelUsuarios.setJLabelDniCif("CIF:");
            panelUsuarios.setEditableJTextFieldWeb(true);
        }
            
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        RecursosApp.guardarDatosClientes();
        ventanaPrincipal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistro;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private poo.javacomp.ventanas.PanelUsuarios panelUsuarios;
    // End of variables declaration//GEN-END:variables
}
